### PR TITLE
Port https://github.com/nextcloud/server/pull/30338

### LINKED ISSUE #13: Port https://github.com/nextcloud/server/pull/30338
https://github.com/nextcloud/server/pull/30338 should have been added here because we'll replace the component with https://github.com/nextcloud/server/pull/29796.

cc @quentinguidee

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
port https://github.com/nextcloud/server/pull/30338
extend .gitignore

fixes #13

### CODE REVIEW

**Comment by JuliaKirschenheuter** [comment]
fixes #13

**Comment by ChristophWurst** [comment]
> fixes #13

I think this need to into the PR description to work.

**Comment by JuliaKirschenheuter** [comment]
@[quentinguid](https://github.com/quentinguidee) we have ported your code

**Comment by ChristophWurst** [comment]
@JuliaKirschenheuter see https://github.com/nextcloud/calendar-availability-vue/pull/16/checks?check_run_id=5271293955. You have to amend your commit and use `-s`/`--sign-off` for the commit.

**Review by ChristophWurst — APPROVED** [review]

**Pull request merged**
